name: Cypress Tests with Artifacts

on: [ push ]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout GitCode
        uses: actions/checkout@v4

      # Étape 3 : Exécuter les tests Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # Spécifiez le chemin vers vos fichiers de test Cypress: npx cypress run --spec 'cypress/e2e/play/pro/v3/*.cy.js'
          working-directory: src/test/java/Cypress
          command: npx cypress run --spec 'cypress/e2e/play/pro/v3/booking/booking2_bc_test_spec.cy.js'
          browser: chrome

      # Étape 4 : Télécharger les captures d'écran en cas d'échec
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: src/test/java/Cypress/cypress/screenshots

      # Étape 5 : Télécharger les vidéos des tests
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: src/test/java/Cypress/cypress/videos
